// ukesoppgave15-react/src/components/QuestionView.tsx
import type { Question } from '../types/quiz';

interface QuestionViewProps {
  question: Question;
  answered: boolean;
  selected: number[] | number;
  onAnswer: (idx: number) => void;
  onNext: () => void;
}

const QuestionView = (props: QuestionViewProps) => {
  const { question, answered, selected, onAnswer, onNext } = props;
  const isCorrect = selected === question.answer;

  return (
    <>
      <h2>{question.question}</h2>
      <ul>
        {question.options.map((option, idx) => (
          <li key={idx}>
            <button disabled={answered} onClick={() => onAnswer(idx)}>
              {option}
            </button>
          </li>
        ))}
      </ul>
      {answered && (
        <div>
          {isCorrect ? (
            <p>Riktig!</p>
          ) : (
            <p>
              Feil. Riktig svar:
              <strong>{question.options[question.answer]}</strong>
            </p>
          )}
          <button onClick={onNext}>Neste spørsmål</button>
        </div>
      )}
    </>
  );
};

export default QuestionView;

// ukesoppgave15-nuxt/components/QuestionView.vue
<template>
  <div>
    <h2>{{ question.question }}</h2>
    <ul>
      <li v-for="(option, idx) in question.options" :key="idx">
        <button :disabled="answered" @click="$emit('answer', idx)">
          {{ option }}
        </button>
      </li>
    </ul>
    <div v-if="answered">
      <p v-if="isCorrect">Riktig!</p>
      <p v-else>
        Feil. Riktig svar:
        <strong>
          {{ question.options[question.answer] }}
        </strong>
      </p>
      <button @click="$emit('next')">Neste spørsmål</button>
    </div>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  question: Question;
  answered: boolean;
  selected: number | null;
}>();

const isCorrect = computed(() => props.selected === props.question.answer);
</script>
