// ukesoppgave15-nuxt/components/QuizSummary.vue
<template>
  <div>
    <h2>Resultat</h2>
    <p>Du fikk {{ correctCount }} av {{ questions.length }} riktige.</p>
    <ul>
      <li v-for="(q, idx) in questions" :key="q.question">
        {{ q.question }}<br />
        <small>
          Ditt svar: {{ q.options[answers[idx]] ?? 'ikke svart' }}<br />
          Riktig: {{ q.options[q.answer] }}
        </small>
      </li>
    </ul>
    <button @click="$emit('restart')">Spill igjen</button>
    <br />
    <router-link to="/">Ta en ny quiz</router-link>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  questions: Question[];
  answers: number[];
}>();

const isCorrectAnswer = (answer: number, index: number) =>
  answer === props.questions[index].answer;
const correctCount = computed(
  () => props.answers.filter(isCorrectAnswer).length
);
</script>

// ukesoppgave15-react/src/components/QuizSummary.tsx
import type { Question, QuizSummaryProps } from '../types/quiz';
import { Link } from 'react-router';

const QuizSummary = (props: QuizSummaryProps) => {
  const { questions, answers, onRestart } = props;

  const isCorrectAnswer = (answer: number, index: number) =>
    answer === props.questions[index].answer;

  const correctCount = answers.filter(isCorrectAnswer).length;

  return (
    <>
      <h2>Resultat</h2>
      <p>
        Du fikk {correctCount} av {questions.length} riktige.
      </p>
      <ul>
        {questions.map((q: Question, idx: number) => (
          <li key={q.question}>
            {q.question}
            <br />
            <small>
              Ditt svar: {q.options[answers[idx]] ?? 'ikke svart'}
              <br />
              Riktig: {q.options[q.answer]}
            </small>
          </li>
        ))}
      </ul>
      <button onClick={onRestart}>Spill igjen</button>
      <br />
      <Link to={'/'}>Ta en ny quiz</Link>
    </>
  );
};

export default QuizSummary;
