// ukesoppgave15-react/src/QuizDetail.tsx
import { quizzes } from './data/quizzes';
import QuestionView from './components/QuestionView.tsx';
import QuizSummary from './components/QuizSummary.tsx';
import { useState } from 'react';
import { useParams } from 'react-router';

const QuizDetail = () => {
  const { id } = useParams<{ id: string }>();
  const [currentQuestion, setCurrentQuestion] = useState<number>(0);
  const [answers, setAnswers] = useState<number[]>([]);
  const [answered, setAnswered] = useState<boolean>(false);

  const quiz = quizzes.find((q) => q.id === id);

  function answerQuestion(selectedIdx: number) {
    answers[currentQuestion] = selectedIdx;
    setAnswered(true);
  }

  function nextQuestion() {
    setAnswered(false);
    setCurrentQuestion(currentQuestion + 1);
  }

  function restart() {
    setCurrentQuestion(0);
    setAnswers([]);
    setAnswered(false);
  }

  if (!quiz) {
    return (
      <div>
        <p>Quiz ikke funnet.</p>
      </div>
    );
  }

  return (
    <>
      <h1>{quiz.title}</h1>
      {currentQuestion < quiz.questions.length ? (
        <QuestionView
          question={quiz.questions[currentQuestion]}
          answered={answered}
          selected={answers[currentQuestion]}
          onAnswer={answerQuestion}
          onNext={nextQuestion}
        />
      ) : (
        <QuizSummary
          questions={quiz.questions}
          answers={answers}
          onRestart={restart}
        />
      )}
    </>
  );
};

export default QuizDetail;

// ukesoppgave15-nuxt/pages/QuizDetail.vue
<script setup lang="ts">
const props = defineProps<{ quizId: string }>();
const quiz = computed(() => quizzes.find((q) => q.id === props.quizId));

const currentQuestion = ref(0);
const answers = ref<number[]>([]);
const answered = ref(false);

function answerQuestion(selectedIdx: number) {
  answers.value[currentQuestion.value] = selectedIdx;
  answered.value = true;
}
function nextQuestion() {
  answered.value = false;
  currentQuestion.value++;
}

function restart() {
  currentQuestion.value = 0;
  answers.value = [];
  answered.value = false;
}

watch(() => props.quizId, restart);
</script>

<template>
  <div v-if="quiz">
    <h1>{{ quiz.title }}</h1>
    <div v-if="currentQuestion < quiz.questions.length">
      <QuestionView
        :question="quiz.questions[currentQuestion]"
        :answered="answered"
        :selected="answers[currentQuestion]"
        @answer="answerQuestion"
        @next="nextQuestion"
      />
    </div>
    <QuizSummary
      v-else
      :questions="quiz.questions"
      :answers="answers"
      @restart="restart"
    />
  </div>
  <div v-else>
    <p>Quiz ikke funnet.</p>
  </div>
</template>
